# -*- coding: utf-8 -*-
"""02_sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1exPTdeaWt0CQs7v2AZpPza7W-wUXYTsa
"""

pip install pandas pyreadr transformers torch tqdm

from google.colab import drive
drive.mount('/content/drive')

import pyreadr
import pandas as pd
import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from tqdm import tqdm

# Set up device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Load .RDS file
rds_path = "WP_2015foodexample.RDS"  # <- Replace with your RDS file path
result = pyreadr.read_r(rds_path)
df = next(iter(result.values()))

# Check if 'snippet' column exists
if 'snippet' not in df.columns:
    raise ValueError("The column 'snippet' was not found in the RDS file.")

# Load Cardiff NLP model and tokenizer
model_name = "cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name).to(device)
model.eval()

labels = ['negative', 'neutral', 'positive']

# Sentiment scoring function (GPU-aware)
def get_sentiment_scores(text):
    try:
        tokens = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(device)
        with torch.no_grad():
            output = model(**tokens)
            probs = F.softmax(output.logits, dim=1)[0].cpu()
        return {label: float(probs[i]) for i, label in enumerate(labels)}
    except Exception as e:
        print(f"Error processing: {text[:50]}... → {e}")
        return {label: None for label in labels}

# Apply to all snippets
tqdm.pandas()
sentiment_scores = df['snippet'].astype(str).progress_apply(get_sentiment_scores)
scores_df = pd.DataFrame(sentiment_scores.tolist())

# Combine with original data
df_out = pd.concat([df, scores_df], axis=1)

df_out.head()

# Calculate sentiment intensity score (normalized to 0–1)
df_out["sentiment_score"] = (
    (df_out["positive"] - df_out["negative"]) /
    (df_out["positive"] + df_out["neutral"] + df_out["negative"])
)

# This score:
# Reflects direction: positive values = more positive emotion; negative = more negative
# Reflects intensity: larger values = stronger sentiment (either direction)
# Ranges from -1 to +1

df_out.head()

# Save output to CSV
df_out.to_csv("output/sentiment/rds_sentiment_output.csv", index=False)
print("Saved results to rds_sentiment_output.csv")